server:
  port: 80

spring:
  application:
    name: buddlebuddy

  datasource:
    url:  jdbc:mysql://buddledb.cvptame2b3q9.ap-northeast-2.rds.amazonaws.com:3306
    username: admin
    password: buddlebuddy
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql 8버전
  # driver-class-name: com.mysql.jdbc.Driver # mysql 5버전

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        #     show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
  sql:
    init:
      platform: mysql
logging.level:
  org.hibernate.SQL: debug
  #  org.hibernate.type: trace