server:
  port: 8090

spring:
  application:
    name: buddlebuddy

  profiles:
    include: oauth

  datasource:
    url:  jdbc:mysql://buddledb.cvptame2b3q9.ap-northeast-2.rds.amazonaws.com:3306/buddleDB
    username: admin
    password: buddlebuddy
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql 8버전

  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        #     show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
  sql:
    init:
      platform: mysql
logging.level:
  org.hibernate.SQL: debug
  #  org.hibernate.type: trace