spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 457274309020-vg44c62ho2ov2eir9uv8gmqrq6jqdm88.apps.googleusercontent.com
            client-secret: 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
            scope: profile,email